import Note from './components/Note'


const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note => 
          <Note key={note.id} note={note} />
        )}
      </ul>
    </div>
  )
}
// make each ote into a li element
// list items, generated by the map method, must each have a unique key
// value, an attr called key
//React uses the key attributes of objects in an array to determine how to update the view generated 
//by a component when the component is re-rendered. 
export default App
